### ISSUE TITLE
Add AARCH64 Support

### ISSUE THREAD

**Issue by SeboKnt** [samba-in-kubernetes/samba-container#155]
Hi, on my K8s cluster on the x86/Ubuntu nodes it works fine (thanks for that) but it's a multi-arch cluster and I can't migrate the container to my arm64/Alpine nodes. Are there any plans to make the container available for arm architecture?

**Comment by apexkode** [comment]
Hi I would also like support for arm64 arch, however I am struggling to build with the instructions provided, is there a timeline for when arm64 builds will be available on quay.io?

**Comment by anoopcs9** [comment]
> Hi I would also like support for arm64 arch, however I am struggling to build with the instructions provided,

What are the issues you have seen with podman by running `make BUILD_ARCH=arm64 build-server`?

**Comment by apexkode** [comment]
@anoopcs9  I encountered the same issue described here: https://github.com/containers/podman/issues/18483
Which does not seem to be directly related to this project but rather an issue in podman and Fedora (possibly), but did not yet try the work around which was suggested as I did not want to [rm -rf](https://github.com/containers/podman/issues/18483#issuecomment-1536054770) my container directory, I was going to look further into this when I had more time.

**Comment by phlogistonjohn** [comment]
There's no timeline, sorry.

I don't know if there's a good way to work around the podman issue. I understand your reluctance to simply delete your containers directory. You probably thought of this already, but maybe you could find a different spare node to build on?

FWIW I'd be happy to work with any one who can make contributions to the build scripts in order to start building for arm64 as most of the infrastructure should be there. I just personally don't have the time for it myself right now.

**Comment by mogeko** [comment]
Nowadays, the Arm-based hosted runners in GitHub Actions is in Beta. Perhaps in the near future, we will see the samba-container working on the Arm node.

See:

- https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions
- https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions
