### ISSUE TITLE
Research the need for Samba VFS fileid

### ISSUE THREAD

**Issue by gd** [samba-in-kubernetes/samba-container#49]
We need to check:
* do we need a special fileid handling?
* if yes, is the sufficient vfs_fileid module sufficient?
* if not, we need to code what is missing

**Comment by spuiuk** [comment]
Create ceph bug tracker 
https://tracker.ceph.com/issues/52812

**Comment by spuiuk** [comment]
Patch to fix the fsid of the exported ceph filesystems sent upstream.
https://lore.kernel.org/ceph-devel/20211005153019.79956-1-jlayton@kernel.org/T/#u

**Comment by spuiuk** [comment]
To avoid the fileid differing across nodes, we need to configure samba to use the fsid to build the fileid. This can be done by adding the following directives to smb.conf

[global]
vfs objects = fileid
fileid:algorithm = fsid

Ref:
https://www.samba.org/samba/docs/current/man-html/vfs_fileid.8.html

**Comment by spuiuk** [comment]
Investigating further into how we setup the samba configuration in the samba-container. 
1) The samba configuration is setup in the registry.
2) The sambacc utility parses the accompanying container.json, converts it to smb.conf file and uses "net conf import" to setup the configuration on the samba server

We need to add the above directives for cephfs filesystems.

We can either
1)  Modify the current examples/minimal.json file and add the directives there. or 
2) Provide a way to modify the existing configuration to add new configuration directives.

For example, in the case of a cephfs backend, we will need to run the following commands.
net conf setparm global "vfs objects" "fileid"
net conf setparm global "fileid:algorithm" "fsid"

I propose we extend the sambacc functionality so that the new parameters can be added in the following manner
samba-container setparm global  "vfs objects" "fileid"
samba-container setparm global "fileid:algorithm" "fsid"

**Comment by spuiuk** [comment]
vfs_fileid changes merged. Closing this issue.

**Comment by phlogistonjohn** [comment]
closing for real ;-)
